import { describe, expect, it } from 'vitest';
import { PLATYCOSMS } from '../src/data/platycosms';
import { Gamma, enumerate } from '../src/math/group';
import { Iso, apply, compose, key, screwOf } from '../src/math/iso';
import { Vec3, dist, mean } from '../src/math/vec';
import { analyze } from '../src/math/analyze';

describe('lattice x coset construction equals the group generated by the generators', () => {
  for (const P of PLATYCOSMS) {
    it(P.id, () => {
      const G = new Gamma(P.gens, P.lattice);
      const c = mean(P.dom().V);
      const p: Vec3 = [0.1, 0.2, 0.3];
      const radius = 2.2;
      const built = new Set(G.near(c, p, radius).map(key));
      const bfs = enumerate(P.gens, 10, 6).filter((g) => dist(apply(g, c), p) <= radius);
      for (const g of bfs) expect(built.has(key(g))).toBe(true);
      // and conversely every constructed element is generated (the lattice basis is exactly the translation subgroup)
      const generated = new Set(enumerate(P.gens, 12, 7).map(key));
      for (const g of G.near(c, p, 1.6)) expect(generated.has(key(g))).toBe(true);
    });
  }
});

describe('the three animation generators generate the whole group', () => {
  for (const P of PLATYCOSMS) {
    it(P.id, () => {
      const full = new Set(enumerate(P.gens, 10, 3).map(key));
      const few = new Set(enumerate([...P.animGens], 12, 3).map(key));
      for (const k of full) expect(few.has(k)).toBe(true);
    });
  }
});

describe('screw decomposition reproduces the isometry', () => {
  it('works for every proper generator', () => {
    for (const P of PLATYCOSMS) for (const g of P.animGens) {
      if (g.A[0] * (g.A[4] * g.A[8] - g.A[5] * g.A[7]) < 0 && false) continue;
      const det = g.A[0] * (g.A[4] * g.A[8] - g.A[5] * g.A[7]) - g.A[1] * (g.A[3] * g.A[8] - g.A[5] * g.A[6]) + g.A[2] * (g.A[3] * g.A[7] - g.A[4] * g.A[6]);
      if (det < 0) continue;
      const s = screwOf(g);
      const th = (s.angle * Math.PI) / 180, [x, y, z] = s.axis, c = Math.cos(th), sn = Math.sin(th);
      const R: Iso = { // Rodrigues
        A: [c + x * x * (1 - c), x * y * (1 - c) - z * sn, x * z * (1 - c) + y * sn,
          y * x * (1 - c) + z * sn, c + y * y * (1 - c), y * z * (1 - c) - x * sn,
          z * x * (1 - c) - y * sn, z * y * (1 - c) + x * sn, c + z * z * (1 - c)],
        t: [0, 0, 0],
      };
      const probe: Vec3 = [0.3, -0.7, 1.1];
      const rel: Vec3 = [probe[0] - s.point[0], probe[1] - s.point[1], probe[2] - s.point[2]];
      const rot = apply(R, rel);
      const got: Vec3 = [rot[0] + s.point[0] + s.axis[0] * s.slide, rot[1] + s.point[1] + s.axis[1] * s.slide, rot[2] + s.point[2] + s.axis[2] * s.slide];
      expect(dist(got, apply(g, probe))).toBeLessThan(1e-9);
    }
  });
  it('compose/inverse sanity', () => {
    const g = PLATYCOSMS[5].animGens[0];
    expect(key(compose(g, g))).toBeTruthy();
  });
});

describe('analysis still passes with the full enumeration', () => {
  it('c22', () => expect(analyze(PLATYCOSMS[5], { samples: 100 }).ok).toBe(true));
});
