import { FAMILY_LABEL, factsFor } from '../data/facts';
import { describeIso } from '../math/gluing';
import { edgeColor, vertColor } from '../render/palette';
import type { Stage } from '../render/stage';
import type { Mode } from '../render/stage';

const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');

/** Fill the notes column for the platycosm currently shown, and wire up its controls. */
export function renderPanel(el: HTMLElement, stage: Stage, mode: Mode): void {
  const e = stage.entry;
  if (!e) return;
  const { def, R, pairs } = e;
  const F = factsFor(def.id);
  const nE = Array(R.nEdgeClasses).fill(0), nV = Array(R.nVertexClasses).fill(0);
  R.eClass.forEach((c) => nE[c]++);
  R.vClass.forEach((c) => nV[c]++);
  const edges = nE.map((k, i) => `<span class="chip"><span class="bar" style="background:${edgeColor(i)}"></span>×${k}</span>`).join('');
  const verts = nV.map((k, i) => `<span class="chip"><span class="dot" style="background:${vertColor(i)}"></span>×${k}</span>`).join('');
  const nSeams = R.isSeam.filter(Boolean).length;

  const pairHtml = pairs.map((p, i) => {
    const same = p.a.face === p.b.face;
    const label = same ? `${p.a.name} (its halves)` : `${p.a.name} ↔ ${p.b.name}`;
    return `<li tabindex="0" data-pair="${i}"><span class="f">${label}</span><span class="k">${p.kind}${p.count > 1 ? ` ×${p.count}` : ''}</span></li>`;
  }).join('');

  const gens = def.animGens.map((g, i) =>
    `<button type="button" data-gen="${i}" aria-pressed="false"><span class="n">Symmetry ${i + 1}</span><span>${esc(describeIso(g))}</span></button>`).join('');

  const seifert = F.seifert.map((s) => `${s.count}: ${s.type}`).join('; ');
  el.innerHTML = `
    <div>
      <h2>${def.name}<span class="sym">${def.sym}</span></h2>
      <p class="fam">${FAMILY_LABEL[F.family]}${F.otherNames.length ? ' · also: ' + F.otherNames.join(', ') : ''}</p>
    </div>
    <div class="glance">
      <p><span class="badge">${def.orientable ? 'orientable' : 'non-orientable'}</span>${F.metachiral ? '<span class="badge">two mirror-image forms</span>' : ''}${F.mappingTorus.is ? '<span class="badge mt">mapping torus</span>' : '<span class="badge">not a mapping torus</span>'}</p>
      <p><b>Mapping torus.</b> ${F.mappingTorus.text}</p>
      ${!def.orientable ? `<p><b>Orientable double cover:</b> ${F.orientableDoubleCover}.</p>` : ''}
      <p><b>H₁</b> = ${F.h1} &nbsp; · &nbsp; <b>holonomy</b> of order ${F.holonomyOrder} (point group ${F.pointGroup})</p>
    </div>
    <div class="key">
      <h3>Generated by three symmetries</h3>
      <p class="note">${mode === 'outside'
        ? 'Play one: a ghost copy of the cell moves by that symmetry onto the neighbouring cell. Matching colours and arrows land on each other.'
        : 'Play one: every copy of the cell moves by that symmetry. The whole tiling lands on itself, each crab arriving where another was.'}</p>
      <div class="gens">${gens}</div>
      <div class="player"><button type="button" id="aPlay">Play</button><input type="range" id="aSlide" min="0" max="1000" value="0" aria-label="Animation progress"></div>
    </div>
    <div class="key">
      <h3>Faces glued to each other</h3>
      <ul class="pairs">${pairHtml}</ul>
      ${nSeams ? `<p class="note">${nSeams} extra edge${nSeams > 1 ? 's' : ''} (tubes lying inside a face) cut a face into halves so that each half is glued whole to another half.</p>` : ''}
    </div>
    <div class="key"><h3>Edges (copies on the cell)</h3><div class="chips">${edges}</div></div>
    <div class="key"><h3>Vertices (copies on the cell)</h3><div class="chips">${verts}</div></div>
    ${F.metachiral ? '<p class="note">The screw can turn either way; the two choices are mirror images.</p>' : ''}
    <details>
      <summary>More from the paper</summary>
      <dl>
        <dt>Space group</dt><dd>${F.spaceGroup}</dd>
        <dt>Wolf</dt><dd>${F.wolf}</dd>
        <dt>π₁</dt><dd>${esc(F.pi1)}</dd>
        <dt>Shape parameters</dt><dd>${F.shapeParameters}</dd>
        <dt>Seifert fibrations</dt><dd>${esc(seifert)}</dd>
        <dt>Embedded flat surfaces</dt><dd>${esc(F.surfaces)}</dd>
        <dt>Double covers</dt><dd>${F.doubleCovers.total}: ${F.doubleCovers.types}</dd>
        <dt>Bravais types</dt><dd>${F.bravaisTypes}</dd>
        <dt>Injectivity radius²</dt><dd>${esc(F.injectivityRadiusSq)}</dd>
        <dt>Diameter²</dt><dd>${esc(F.diameterSq)}</dd>
      </dl>
      <p class="note">Parameters A, B, C, D are the paper's. Every fact is sourced in NOTES.md in the repository.</p>
    </details>`;

  // hover a pairing: highlight its faces on the cell
  el.querySelectorAll<HTMLElement>('.pairs li').forEach((li) => {
    const polys = pairs[Number(li.dataset.pair)].polys;
    ['mouseenter', 'focus'].forEach((ev) => li.addEventListener(ev, () => stage.highlight(polys)));
    ['mouseleave', 'blur'].forEach((ev) => li.addEventListener(ev, () => stage.highlight(null)));
  });

  // symmetry animation controls
  const play = el.querySelector<HTMLButtonElement>('#aPlay')!;
  const slide = el.querySelector<HTMLInputElement>('#aSlide')!;
  const genBtns = [...el.querySelectorAll<HTMLButtonElement>('[data-gen]')];
  genBtns.forEach((b) => b.addEventListener('click', () => { stage.anim.start(Number(b.dataset.gen)); stage.applyOptions(); }));
  play.addEventListener('click', () => {
    const a = stage.anim;
    if (a.gen === null) a.start(0);
    else if (a.playing) a.pause();
    else a.resume();
  });
  slide.addEventListener('input', () => { if (stage.anim.gen === null) stage.anim.start(0); stage.anim.scrub(Number(slide.value) / 1000); });
  stage.onFrame = () => {
    const a = stage.anim;
    genBtns.forEach((b) => b.setAttribute('aria-pressed', String(a.gen === Number(b.dataset.gen))));
    play.textContent = a.gen !== null && a.playing ? 'Pause' : 'Play';
    if (document.activeElement !== slide) slide.value = String(Math.round(a.tau * 1000));
  };
}
