import { Iso, IDENTITY, apply, compose, inverse, key } from './iso';
import { Vec3, len, sub } from './vec';

/**
 * Breadth-first enumeration of the group generated by `gens`, keeping elements with |t| <= maxT.
 * Used for analysis (small radius) and as an independent check of `coset` below.
 */
export function enumerate(gens: Iso[], maxDepth = 8, maxT = 4): Iso[] {
  const all = gens.concat(gens.map(inverse));
  const seen = new Map<string, Iso>([[key(IDENTITY), IDENTITY]]);
  let frontier: Iso[] = [IDENTITY];
  for (let d = 0; d < maxDepth && frontier.length; d++) {
    const next: Iso[] = [];
    for (const g of frontier) for (const s of all) {
      const h = compose(s, g), k = key(h);
      if (seen.has(k) || len(h.t) > maxT) continue;
      seen.set(k, h);
      next.push(h);
    }
    frontier = next;
  }
  return [...seen.values()];
}

/** One representative per distinct linear part (the holonomy group), with the smallest translation. */
export function holonomyReps(gens: Iso[]): Iso[] {
  const els = enumerate(gens, 8, 3);
  const best = new Map<string, Iso>();
  for (const g of els) {
    const k = g.A.map((v) => Math.round(v * 1e4)).join(',');
    const old = best.get(k);
    if (!old || len(g.t) < len(old.t) - 1e-9) best.set(k, g);
  }
  return [...best.values()];
}

const inv3 = (m: number[]): number[] => {
  const [a, b, c, d, e, f, g, h, i] = m;
  const D = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g);
  return [
    (e * i - f * h) / D, (c * h - b * i) / D, (b * f - c * e) / D,
    (f * g - d * i) / D, (a * i - c * g) / D, (c * d - a * f) / D,
    (d * h - e * g) / D, (b * g - a * h) / D, (a * e - b * d) / D,
  ];
};

/**
 * The group as lattice x coset representatives: every element is T(lambda) after rep, lambda in the translation lattice.
 * `basis` are the lattice basis vectors. Returns the elements whose image of `c` lies within `radius` of `p`.
 */
export class Gamma {
  readonly reps: Iso[];
  private readonly Binv: number[]; // inverse of the matrix whose columns are the basis vectors
  constructor(readonly gens: Iso[], readonly basis: [Vec3, Vec3, Vec3]) {
    this.reps = holonomyReps(gens);
    const [u, v, w] = basis;
    this.Binv = inv3([u[0], v[0], w[0], u[1], v[1], w[1], u[2], v[2], w[2]]);
  }
  /** Elements gamma with |gamma(c) - p| <= radius. */
  near(c: Vec3, p: Vec3, radius: number): Iso[] {
    const out: Iso[] = [];
    const [u, v, w] = this.basis, Bi = this.Binv;
    // |row_i of Binv| bounds how far n_i can stray from the centre for a given radius
    const rowLen = [0, 1, 2].map((i) => Math.hypot(Bi[3 * i], Bi[3 * i + 1], Bi[3 * i + 2]));
    for (const r of this.reps) {
      const target = sub(p, apply(r, c)); // we need lambda close to this
      const n0 = [0, 1, 2].map((i) => Bi[3 * i] * target[0] + Bi[3 * i + 1] * target[1] + Bi[3 * i + 2] * target[2]);
      const m = rowLen.map((l) => Math.ceil(radius * l) + 1);
      for (let i = Math.round(n0[0]) - m[0]; i <= Math.round(n0[0]) + m[0]; i++)
        for (let j = Math.round(n0[1]) - m[1]; j <= Math.round(n0[1]) + m[1]; j++)
          for (let k = Math.round(n0[2]) - m[2]; k <= Math.round(n0[2]) + m[2]; k++) {
            const lam: Vec3 = [i * u[0] + j * v[0] + k * w[0], i * u[1] + j * v[1] + k * w[1], i * u[2] + j * v[2] + k * w[2]];
            const g: Iso = { A: r.A, t: [r.t[0] + lam[0], r.t[1] + lam[1], r.t[2] + lam[2]] };
            if (len(sub(apply(g, c), p)) <= radius) out.push(g);
          }
    }
    return out;
  }
}
